### ISSUE TITLE
Old Game Titles

### ISSUE THREAD

**Issue by SushantSharma1992** [AnimMouse/psn-pkg-torrents#3]
Hello ,

I read in the readme file that if you need a game create an issue.

I searched everywhere but was unable to find 

**Heavenly Sword** and **Blur** for PS3.

I was really hoping if you could create torrents for those titles.

**Comment by AnimMouse** [comment]
For Heavenly Sword, there is a PKG for ASIA region, but the problem is, you probably cannot play this game because RAP file does not exist. There is also a PKG for EU region, but it is a demo version.
For Blur, PKG file does not exist, the game is released only on Blu-ray, not on digital distribution, so I cannot provide it, even NoPayStation.

But if you want to play Heavenly Sword and Blur, you can use the CFW2OFW method because those games are supported, but you gonna need the ISO file and I'm not gonna upload it here because it is kinda.... illegal.

**Comment by SushantSharma1992** [comment]
I would really appreciate if you could guide me to the Heavenly Sword PKG for ASIA region, 
or sources or both if possible.

**Comment by AnimMouse** [comment]
Here it is: [https://nopaystation.com/view/PS3/NPEA90016/HEAVENLYSWORDPSN/0?version=1](https://nopaystation.com/view/PS3/NPEA90016/HEAVENLYSWORDPSN/0?version=1)

I will probably make a torrent of this after I finish downloading it.

**Comment by SushantSharma1992** [comment]
Thank you very much....

**Comment by AnimMouse** [comment]
Done. 4526a29
